apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews-service
  template:
    metadata:
      labels:
        app: reviews-service
    spec:
      containers:
        - name: reviews-service
          image: reviews-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8082

---

apiVersion: v1
kind: Service
metadata:
  name: reviews-service
spec:
  selector:
    app: reviews-service
  ports:
    - port: 8082
      targetPort: 8082